oucrc-org/web-2021

- layouts/error.vue
- package-lock.json
デザイン分かんないので、誰かイカしたデザインにしてくれ・・・
Close #8
> [add] 404ページを追加

- components/Button.vue
使い方例
<Button class="mx-auto w-4/5" label="この記事を読む" />
> [feature] Buttonコンポーネントを作成

- components/Header.vue
- pages/index.vue
つまり
```
- position: fixed;
+ position: sticky;
+ top: 0;
```
> [refactor] ヘッダーが本文に重ならないようにした

- components/Header.vue
ナビゲーションバーが、どこでもhomeのところにも線が引かれてたので修正
> [fix] 該当部分を修正

- components/Contact.vue
> [fix] ボタン関連を修正

- pages/index.vue
> ランディングページお知らせ関連の細かい修正

- assets/images/cancel.svg
- components/Header.vue
> [add] スマホ用のナビゲーションを追加

- pages/members/index.vue
> [fix] ルートを修正

- nuxt.config.js
- package-lock.json
- package.json
> [add] Google Analytics 追加

- nuxt.config.js
> [add] Google Search Console

- pages/members/_id.vue
> [add] 自己紹介画像 追加

- pages/article/_id.vue
- pages/news/_id.vue
> [fix] article.imageのundefinedチェックを修正

- components/ArticleContent.vue
> [fix] 記事 1行コードブロック 修正

- pages/members/_id.vue
> [fix] urlを修正

- components/LabeledCheckbox.vue
- pages/article/index.vue
> [add] カテゴリー&シリーズ クリック時に検索

- pages/members/_id.vue
> [fix] 部員紹介のhtmlタグの適用

- pages/articles/_id.vue
- pages/index.vue
- pages/members/_id.vue
- pages/news/_id.vue
> [fix] console.logを削除

- components/ArticleCard.vue
- pages/index.vue
> [fix] ランディング カード修正

- assets/mixins/const.js
どうにもできなかったのでとりあえずランディングの画像が出てこないところのみ修正しました。
確認お願いいたします。
> [fix] ランディングのOGPに画像をセット

- pages/index.vue
/articles?category=noi18t4xa3 => /articles/category/noi18t4xa3
> [fix] ランディングからの遷移をパラメータからスラッシュリンクに修正

- pages/index.vue
- pages/news/index.vue
NuxtLinkになってないので静的化されなかったのとnewsの上限値が10になってたのを修正
> [fix] 「部室に何があるの？」にアクセスできない不具合を修正

- nuxt.config.js
- package-lock.json
- package.json
> [hotfix] series, category でのリロードエラーの修正

- assets/css/index.css
- assets/css/index.scss
- nuxt.config.js
- package-lock.json
- package.json
どさくさに紛れてSass(SCSS)導入しました
Webpackがpackage.jsonで明示されてるのはNuxtと競合してバージョン指定する必要があったからです
> Fix: WindowsのChromeでスクロールバーが表示され続けていた問題を修正

- components/Contact.vue
- components/DoubleLineButton.vue
- components/Footer.vue
- components/ValidationIndicator.vue
- layouts/default.vue
- pages/contact/index.vue
- お問い合わせの四角を #178 に従って高くしました
- フォームはリアルタイムでバリデーションしています
> 問い合わせフォームを追加、地図左のパーツのデザイン変更

- components/ArticleContent.vue
- pages/articles/_id.vue
> fix: 無駄なパース警告を削除、generate中のエラーメッセージ改善

- components/ArticleCard.vue
- components/News.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/articles/_id.vue
- pages/articles/index.vue
- pages/index.vue
- pages/members/_id.vue
- pages/members/index.vue
- pages/news/_id.vue
- pages/news/index.vue
SDGs 57015: nuxt.config.js をいじくりまわして Eager loading を実現することで、細かい fetch をなくそう
細かい話は [Nuxt 2 のドキュメントの payload の部分](https://v2.nuxt.com/docs/configuration-glossary/configuration-generate/#speeding-up-dynamic-route-generation-with-payload) を読め
手がかりは作ったのであとは頼んだ
> nuxt generate で記事ページがうまく生成できない問題を解消 (したい)
